config/routes.rb
Panoply::Application.routes.draw do

  constraints(SubdomainConstraint) do
    resources :appointments, only: [ :index ]
    resources :requests, only: [ :new, :create ] do
      collection do
        get 'new/:slot', to: :new, as: :make
      end
    end
    root to: 'appointments#index'
  end

  resources :subscriptions, only: [ :create, :new ]
  match 'appointments', to: redirect('/')
  root to: "home#index"
  devise_for :users

end

app/models/availability.rb
# Availability has:
#  - one provider (User instance)
#  - many appointment requests (AppointmentRequest collection)
#     * User can approve or deny requests
#  - a start time (Datetime)
#  - an end time (Datetime)
#
class Availability < ActiveRecord::Base

  attr_accessible :ends_on, :provider, :starts_on

  belongs_to :provider, class_name: 'User'

  class << self
    def slot_time_for attributes
      create attributes
    end
  end

end

app/models/membership.rb
class Membership < ActiveRecord::Base

  attr_accessible :tenant, :user

  belongs_to :user
  belongs_to :tenant

  class << self
    def make user, tenant
      create user: user, tenant: tenant
    end
  end

end

app/models/request.rb
class Request < ActiveRecord::Base

  attr_accessible :availability, :availability_id, :sender

  belongs_to :sender, class_name: 'User'
  belongs_to :availability

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :stripe_token, :owner

  validates :stripe_token, presence: true

  belongs_to :owner, class_name: 'User'
  has_many :tenants
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base

  attr_accessible :name, :domain, :subscription

  has_many :memberships
  has_many :members, through: :memberships, source: :user
  belongs_to :subscription

  before_create :assign_domain

  private

  def assign_domain
    self[:domain] = name.parameterize
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation,
    :remember_me

  has_many :availabilities, foreign_key: :provider_id
  has_many :memberships
  has_many :tenancies, through: :memberships, source: :tenant
  has_many :subscriptions, foreign_key: :owner_id
  has_many :owned_tenancies, through: :subscriptions, source: :tenants

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  before_filter :remove_subdomain_on_vacancy

  protected

  def remove_subdomain_on_vacancy
    url = root_url subdomain: 'www'
    redirect_to(url) if has_subdomain? && tenant.blank?
  end

  def tenant
    @tenant ||= find_tenant
  end
  helper_method :tenant

  def members
    tenant.present? ? tenant.members : []
  end
  helper_method :members

  def find_tenant
    Tenant.where(domain: request.subdomain).first
  end

  def has_subdomain?
    SubdomainConstraint.matches? request
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def create
    if request_form.submit
      redirect_to root_path, notice: request_form.notice
    else
      render :new
    end
  end

  protected

  def request_form
    @request_form ||= request_form_class.new user: current_user,
      params: request_params, session: session, controller: self
  end
  helper_method :request_form

  def request_params
    request_form_params = params.fetch(:request_form) { Hash.new }
    slot_params = { 'slot_id' => params[:slot] }
    slot_params.merge(request_form_params).symbolize_keys
  end

  def request_form_class
    form_target = params.fetch(:form_target) { 'confirm' }
    [form_target, "request_form"].join("_").camelize.constantize
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    if subscription_form.submit
      redirect_to root_path, notice: "You have been subscribed!"
    else
      render :new
    end
  end

  protected

  def subscription_form
    @subscription_form ||= SubscriptionForm.new params: subscription_params,
      session: session, controller: self
  end
  helper_method :subscription_form

  def subscription_params
    params.fetch(:subscription_form) { Hash.new }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper

  def this_month
    Date.today.strftime("%B, %Y")
  end

  def calendar &block
    CalendarPresenter.new self, Date.today, block
  end

  def calendar_tag &block
    calendar(&block).week_lists
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resource_helper.rb
module ResourceHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/time_slot_helper.rb
module TimeSlotHelper

  def time_slots_for_today member
    range = Date.today.beginning_of_day..Date.today.end_of_day
    Availability.where starts_on: range, provider_id: member.id
  end

  def time_slots providers, date, &block
    TimeSlotPresenter.new self, providers, date, block
  end

  def time_slot_tag providers, date, &block
    time_slots(providers, date, &block).list
  end

end

app/views/appointments/index.html.haml
.calendar-page
  %h2 Book an appointment with #{tenant.name}
  %ul.calendar-page-list
    - members.each do |member|
      %li.calendar-page-list-item
        %span.calendar-page-list-item-label= member.name
        %ul
          - time_slots_for_today(member).each do |slot|
            %li.calendar-page-time-slot= link_to slot.starts_on.strftime("%l:%M %P"), make_requests_path(slot)
  .calendar-page-date-label= Date.today.strftime("%e")

app/views/home/index.html.haml
- unless user_signed_in?
  .form-card
    %h2 You're too busy to spend every day worrying about this
    = button_to "Subscribe today", new_subscription_path, method: 'get'
  = render 'devise/shared/new_registration'

app/views/layouts/_errors.html.haml
- if collection.any?
  #error_explanation
    %h2 We had some problems
    %ul
      - collection.each do |error|
        %li= error

app/views/layouts/_lorem.html.haml
%p In the right hands, a novel’s beginning alone can make you feel like you’ve just fallen into a fast-flowing river, snatched away from reality and hurtled downhill. They range from hard-boiled pulp fiction to classics to, well, The Bible; the only thing they have in common is that they’re so good it’s impossible not to read on. Unfortunately, right now you can’t. But in the meantime, enjoy the best literary handshakes of all time…

app/views/layouts/_messages.html.haml
- flash.each do |name, message|
  - if message.is_a?(String)
    = content_tag :div, message, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
%h1.headline= link_to "Panoply", root_path
#navigation
  %ul
    - if user_signed_in?
      %li= link_to 'Profile', edit_user_registration_path
      %li= link_to 'Logout', destroy_user_session_path, method: 'delete'
    - else
      %li= link_to 'Login', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : "Panoply"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body.fiddlehead-fern
    %header
      = render 'layouts/navigation'
    #container
      = render 'layouts/messages'
      = yield
    %footer

app/views/requests/new.html.haml
= render 'layouts/errors', collection: request_form.errors.full_messages
.form-card
  - if user_signed_in?
    = form_for request_form, url: requests_path do |form|
      = form.hidden_field :slot_id
      = hidden_field_tag :form_target, 'confirm'
      %h2 Confirm your password to request an appointment
      .form-password= form.password_field :password, placeholder: 'Password'
      .form-button= form.submit "Send request"
  - else
    #signup-request-form
      = form_for request_form, url: requests_path do |form|
        = form.hidden_field :slot_id
        = hidden_field_tag :form_target, 'signup'
        %h2 Need an account?
        .form-name= form.text_field :name, placeholder: 'What is your name?'
        .form-email= form.email_field :email, placeholder: 'What is your email address?'
        .form-password= form.password_field :password, placeholder: 'Create a password'
        .form-password= form.password_field :password_confirmation, placeholder: 'Confirm your password'
        .form-button= form.submit "Sign up and request"
    #login-request-form
      = form_for request_form, url: requests_path do |form|
        = form.hidden_field :slot_id
        = hidden_field_tag :form_target, 'login'
        %h2 Have an account?
        .form-email= form.email_field :email, placeholder: 'What is your email address?'
        .form-password= form.password_field :password, placeholder: 'Create a password'
        .form-button= form.submit "Log in and request"

app/views/subscriptions/new.html.haml
= javascript_include_tag 'https://js.stripe.com/v2'

= render 'layouts/errors', collection: subscription_form.errors.full_messages

.form-card
  %h2 Get started
  #subscription-form
    = form_for subscription_form, url: subscriptions_path do |form|
      = form.hidden_field :stripe_token
      .form-name= form.text_field :name, placeholder: 'What is your name?'
      .form-email= form.email_field :email, placeholder: 'What is your email address?'
      .form-name= form.text_field :organization_name, placeholder: "What is your organization's name?"
      .form-password= form.password_field :password, placeholder: 'Create a password'
      .form-password= form.password_field :password_confirmation, placeholder: 'Confirm your password'
      - if subscription_form.stripe_token.present?
        %h3 Your credit information has already been approved.
      - else
        .form-card-info
          %input#card-number{ placeholder: 'XXXX-XXXX-XXXX-XXXX', type: 'text', size: 24, data: { stripe: 'number' } }
          %input#card-code{ placeholder: 'CVC', type: 'text', size: 1, data: { stripe: 'cvc' } }
        .form-card-expiry
          = select_month nil, { add_month_numbers_true: true }, name: nil, "data-stripe" => 'exp-month'
          = select_year nil, { start_year: Date.today.year, end_year: Date.today.year + 15 }, name: nil, "data-stripe" => 'exp-year'
      .form-button= form.submit "Subscribe"

:javascript
  Stripe.setPublishableKey('#{StripeCredentials.public_key}');

  $(document).ready(function() {
    Panoply.Apps.Subscribe.Capture('#subscription-form');
  });